on: 
  pull_request:
    types: [opened, synchronize]

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          *.md

    - name: Set environment
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}  
      run: |
        echo "MD_FILE_PATH=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_ENV

    - name: Validate
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: | 
        npx ts-node --esm validators/md-files-validator/index.ts