on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v12
      with:
        globs: |
          **/*.md
          !LICENSE.md
          !README.md