name: Validate Markdown
on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - name: Validate Markdown
      run: npm run md-validator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}